
#include <iostream>
#include <vector>
#include <math.h> 
#include "TROOT.h"
#include "TFile.h"
#include "TSystem.h"
#include "TChain.h"
#include "TTree.h"
#include "TCut.h"
#include "THStack.h"
#include "TLine.h"
#include "TH1.h"
#include "TH2.h"
#include "TProfile.h"
#include "TFileCollection.h"
#include "TLorentzVector.h"
#include "TPaveText.h"
#include "TKey.h"
#include "TGraphAsymmErrors.h"
#include "inc/make_1D_projections.h"

void fill_fastsim_hists() {
  // example of script to loop on all the objects of a ROOT file directory
  // and print on Postscript all TH1 derived objects
  // This script uses the file generated by tutorial hsimple.C
  //Author: Rene Brun

  // TFile *f0 = TFile::Open("~/Dropbox/Presentations/RA2b/Approval/RA2bin_signal_fastsim.root");
  TFile *f1 = TFile::Open("signal_hists/RA2bin_signal_QCD.root");
  TIter next(f1->GetListOfKeys());
  TKey *key(0);

  TFile* outfile = new TFile("signal_hists/fastsim_signal.root", "recreate");

  double SF=2.262/3.;
   
  int ind(0);
  //double nb3_max(0.);
  while ((key = (TKey*)next())) {
    ind++;
    TClass *cl = gROOT->GetClass(key->GetClassName());
    if (!cl->InheritsFrom("TH1")) continue;
    TObject* obj = key->ReadObj();
    TH1D *hin = (TH1D*)(obj);
    TString hname = Form("%s", hin->GetName());
    // hin->Print("all");
    cout << hname << endl;

    if (hname.Contains("bbbb")) {
      TH1D* hMHT_3b = MakeMHTProjection(hin, 0, 4, 3, 3);
      hMHT_3b->SetName(Form("%s_%s", hMHT_3b->GetName(), hname.Data()));
      hMHT_3b->Scale(SF);
      hMHT_3b->Write();
      TH1D* hNBJets_MHT500 = MakeNBJetsProjection(hin,6,10);
      hNBJets_MHT500->SetName(Form("%s_%s", hNBJets_MHT500->GetName(), hname.Data()));
      hNBJets_MHT500->Scale(SF);
      hNBJets_MHT500->Write();
    }
    else if (hname.Contains("qqqq")) {
      TH1D* hHT_MHT500 = MakeHTProjection(hin, 2, 4, 0, 0, 2, 3);
      hHT_MHT500->SetName(Form("%s_%s", hHT_MHT500->GetName(), hname.Data()));
      hHT_MHT500->Scale(SF);
      hHT_MHT500->Write();
      TH1D* hHT_MHT500_0b_7j = MakeHTProjection(hin, 3, 4, 0, 0, 2, 3);
      hHT_MHT500_0b_7j->SetName(Form("%s_%s", hHT_MHT500_0b_7j->GetName(), hname.Data()));
      hHT_MHT500_0b_7j->Scale(SF);
      hHT_MHT500_0b_7j->Write();
      TH1D* hHT_MHT750 = MakeHTProjection(hin, 0, 4, 0, 0, 3, 3);
      hHT_MHT750->SetName(Form("%s_%s", hHT_MHT750->GetName(), hname.Data()));
      hHT_MHT750->Scale(SF);
      hHT_MHT750->Write();
      TH1D* hHT_7j_0b = MakeHTProjection(hin, 3, 4, 0, 0, 1, 3);
      hHT_7j_0b->SetName(Form("%s_%s", hHT_7j_0b->GetName(), hname.Data()));
      hHT_7j_0b->Scale(SF);
      hHT_7j_0b->Write();
      if (hname.Contains("VV")) {
	TH1D* hNJets_0b_MHT500 = MakeNJetsProjectionV2(hin,0,0,6,10);
	hNJets_0b_MHT500->SetName(Form("%s_%s", hNJets_0b_MHT500->GetName(), hname.Data()));
	hNJets_0b_MHT500->Scale(SF);
	hNJets_0b_MHT500->Write();
      }
    }
    else if (hname.Contains("tttt")) {
      TH1D* hMHT_9j_2b = MakeMHTProjection(hin, 4, 4, 2, 3);
      hMHT_9j_2b->SetName(Form("%s_%s", hMHT_9j_2b->GetName(), hname.Data()));
      hMHT_9j_2b->Scale(SF);
      hMHT_9j_2b->Write();
      TH1D* hNJets_2b = MakeNJetsProjection(hin,22,43);
      hNJets_2b->SetName(Form("%s_%s", hNJets_2b->GetName(), hname.Data()));
      hNJets_2b->Scale(SF);
      hNJets_2b->Write();
    }    
    //outfile->cd();

  
  }
  outfile->Close();
}

